spring:
  datasource:
    url: jdbc:mysql://8.219.62.112:3306/admin_login?useUnicode=true
    username: root
    password: Mao120714
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: ivan
      password: 123456
      roles: admin
  redis:
    host: 8.219.62.112
    port: 6379
    password: 120714
    timeout: 5000
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 80