
name: Raspberry PI Deployment Backend

on:
  push:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up JDK 8
      uses: actions/setup-java@master
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd admin_system_front
        mvn -B package --file pom.xml
        ls -l

